Add missing return type specifier to main
Explicitly set main's return type specifier to int.

As of C99, a declaration that lacks a type specifier isn't implicitly assumed to be int, which causes the build to fail with this error:

    bbcp.C:61:1: error: C++ requires a type specifier for all declarations
    main(int argc, char *argv[], char *envp[])
    ^~~~

Build Environment:
- g++ : Apple LLVM version 5.0 (clang-500.2.76) (based on LLVM 3.3svn)
- OS  : Mac OS X 10.8.5 (Build 12F37)

For the curious, here's the relevant part of the C++11 standard:

> ISO/IEC 14882:2011(E) 3.6.1: Main function
>
> A program shall contain a global function called main, which is the
> designated start of the program. It is implementation-defined whether a
> program in a freestanding environment is required to define a main
> function.
>
> An implementation shall not predefine the main function. This function
> shall not be overloaded. It shall have a return type of type int, but
> otherwise its type is implementation-defined.
>
> First shalt thou declare a function, main. Then shalt thou specify a
> return type of int, no short, no long. Int is the type thou shalt return,
> and the value of the returning shall be int. Void shalt thou not return,
> neither return thou double, and char is right out."

Okay, so I added that last part, but it seemed kind of fitting since the
spec is 84 pages longer than the Gutenberg Bible and 34% more dogmatic. :-)